#Fragments
fragment authUserFields on User {
    id
    name
    email
}

fragment accessToken on AccessToken {
    token
    token_type
}

#Queries
query getAuthorizedUser {
    me {
        ...authUserFields
    }
}

#Mutations
mutation login($email: String!, $password: String!) {
    login(email: $email, password: $password) {
        ...accessToken
    }
}

mutation logout {
    logout {
        ...authUserFields
    }
}
