#Fragments
fragment userFields on User {
    id
    name
    email
    updated_at
    created_at
}

fragment paginatorFields on PaginatorInfo {
    total
    currentPage
    perPage
}

#Queries
query getUsers($page: Int!) {
    users(page: $page) {
        paginatorInfo {
            ...paginatorFields
        }
        data {
            ...userFields
        }
    }
}

query getUser($id: Int!) {
    user (id: $id){
        ...userFields
    }
}

#Mutations
mutation createUser($name: String!, $email: String!, $password: String!) {
    createUser(name: $name, email: $email, password: $password) {
        ...userFields
    }
}

mutation updateUser($id: Int!, $name: String, $email: String, $password: String) {
    updateUser(id: $id, name: $name, email: $email, password: $password) {
        ...userFields
    }
}

mutation deleteUser($id: Int!) {
    deleteUser(id: $id) {
        ...userFields
    }
}

