#Fragments
fragment userFields on User {
    id
    name
    email
}

#Queries
query getUsers($currentPage: Int!) {
    users(page: $currentPage) {
        data {
            ...userFields
        }
    }
}

query getUser($id: Int!) {
    user (id: $id){
        ...userFields
    }
}
